export const restaurantes = [
  {
    slug: "padaria-doce-pao",
    name: "Padaria Doce Pão",
    category: "Padarias",
    description: "Pães, bolos e café passado na hora.",
    status: "Aberto",
    badge: "⭐4.9",
    logo: "/logos/padaria-doce-pao.svg",
    banner: "/banners/padaria-doce-pao.svg",
    address: "Rua das Flores, 123 - Centro",
    hours: "Seg a Dom, 06:30 - 22:00",
    featured: ["Pães artesanais", "Bolos do dia", "Café expresso"],
    menu: [
      { name: "Pão de queijo tradicional", price: "R$ 8,90" },
      { name: "Café coado na hora", price: "R$ 6,50" },
      { name: "Bolo de cenoura com cobertura", price: "R$ 14,90" },
    ],
  },
  {
    slug: "cores-e-sabores",
    name: "Cores e Sabores",
    category: "Doces",
    description: "Sobremesas, brigadeiros e kits presenteáveis.",
    status: "Aberto",
    badge: "⭐4.8",
    logo: "/logos/cores-e-sabores.svg",
    banner: "/banners/cores-e-sabores.svg",
    address: "Av. do Chocolate, 88 - Jardim Doce",
    hours: "Seg a Sáb, 09:00 - 20:00",
    featured: ["Kits presenteáveis", "Brigadeiros gourmet", "Doces finos"],
    menu: [
      { name: "Kit 20 brigadeiros", price: "R$ 67,50" },
      { name: "Caixa com 6 trufas", price: "R$ 21,90" },
      { name: "Brownie com sorvete", price: "R$ 18,90" },
    ],
  },
  {
    slug: "fogao-da-fran",
    name: "Fogão da Fran",
    category: "Marmitas",
    description: "Pratos feitos e marmitas executivas do dia.",
    status: "Aberto",
    badge: "⭐4.7",
    logo: "/logos/fogao-da-fran.svg",
    banner: "/banners/fogao-da-fran.svg",
    address: "Rua da Marmita, 45 - Vila Quente",
    hours: "Seg a Sex, 10:30 - 15:00",
    featured: ["Marmita executiva", "Sobremesa caseira", "Entregas rápidas"],
    menu: [
      { name: "Marmita completa + Coca-Cola 600ml", price: "R$ 26,20" },
      { name: "Frango grelhado com arroz e feijão", price: "R$ 24,90" },
      { name: "Carne bovina com legumes", price: "R$ 28,90" },
    ],
  },
  {
    slug: "veg-saladas",
    name: "Veg Saladas",
    category: "Saudáveis",
    description: "Bowls, saladas frescas e opções leves.",
    status: "Aberto",
    badge: "⭐4.9",
    logo: "/logos/veg-saladas.svg",
    banner: "/banners/veg-saladas.svg",
    address: "Rua Verde, 202 - Parque Natural",
    hours: "Seg a Sáb, 11:00 - 21:00",
    featured: ["Bowls leves", "Ingredientes frescos", "Opções veganas"],
    menu: [
      { name: "Salada proteica", price: "R$ 32,99" },
      { name: "Bowl tropical", price: "R$ 29,90" },
      { name: "Wrap integral", price: "R$ 22,90" },
    ],
  },
  {
    slug: "panda-sushi",
    name: "Panda Sushi",
    category: "Japonesa",
    description: "Combos, temakis e hot rolls bem montados.",
    status: "Aberto",
    badge: "⭐4.8",
    logo: "/logos/panda-sushi.svg",
    banner: "/banners/panda-sushi.svg",
    address: "Av. Sakura, 77 - Bairro Oriental",
    hours: "Ter a Dom, 18:00 - 23:30",
    featured: ["Sushis frescos", "Combos especiais", "Hot rolls"],
    menu: [
      { name: "Combo sushi", price: "R$ 93,78" },
      { name: "Temaki salmão", price: "R$ 24,90" },
      { name: "Hot roll crocante", price: "R$ 21,90" },
    ],
  },
  {
    slug: "pizzaria-da-familia",
    name: "Pizzaria da Família",
    category: "Pizzas",
    description: "Pizzas artesanais com borda recheada.",
    status: "Fechado",
    badge: "⭐4.6",
    logo: "/logos/pizzaria-da-familia.svg",
    banner: "/banners/pizzaria-da-familia.svg",
    address: "Rua do Forno, 310 - Vila Itália",
    hours: "Qua a Dom, 18:00 - 23:00",
    featured: ["Massa artesanal", "Borda recheada", "Promoções da noite"],
    menu: [
      { name: "Pizza tamanho família", price: "R$ 73,99" },
      { name: "Pizza pepperoni", price: "R$ 59,90" },
      { name: "Pizza marguerita", price: "R$ 54,90" },
    ],
  },
  {
    slug: "burger-king",
    name: "Burger King",
    category: "Lanches",
    description: "Hambúrgueres frescos.",
    status: "Fechado",
    badge: "⭐4.1",
    logo: "/logos/burger-king.svg",
    banner: "/banners/burger-king.svg",
    address: "Av. Principal, 1000 - Centro",
    hours: "Seg a Dom, 11:00 - 23:00",
    featured: ["Hambúrgueres", "Batata crocante", "Milk-shakes"],
    menu: [
      { name: "Hambúrguer bacon e queijo", price: "R$ 46,90" },
      { name: "Combo clássico", price: "R$ 39,90" },
      { name: "Batata grande", price: "R$ 16,90" },
    ],
  },
  {
    slug: "churrascaria-do-joelso",
    name: "Churrascaria do Joelso",
    category: "Carnes",
    description: "Carne na chapa.",
    status: "Fechado",
    badge: "⭐5.0",
    logo: "/logos/churrascaria-do-joelso.svg",
    banner: "/banners/churrascaria-do-joelso.svg",
    address: "Estrada da Fumaça, 45 - Zona Rural",
    hours: "Sex a Dom, 11:00 - 22:30",
    featured: ["Carnes nobres", "Chapa na hora", "Porções generosas"],
    menu: [
      { name: "Kit churrasco + Coca-Cola 2l", price: "R$ 217,73" },
      { name: "Picanha na chapa", price: "R$ 89,90" },
      { name: "Alcatra completa", price: "R$ 79,90" },
    ],
  },
  {
    slug: "pizzaria-nativa",
    name: "Pizzaria Nativa",
    category: "Pizzas",
    description: "Pizzas de diversos tamanhos para toda a família.",
    status: "Fechado",
    badge: "⭐4.6",
    logo: "/logos/pizzaria-nativa.svg",
    banner: "/banners/pizzaria-nativa.svg",
    address: "Rua da Lenha, 90 - Bairro Nativo",
    hours: "Qui a Dom, 18:00 - 23:30",
    featured: ["Entrega noturna", "Massa fina", "Combos de pizza"],
    menu: [
      { name: "Pizza especial da casa", price: "R$ 69,90" },
      { name: "Pizza calabresa", price: "R$ 55,90" },
      { name: "Pizza quatro queijos", price: "R$ 57,90" },
    ],
  },
];

export function getRestaurantBySlug(slug) {
  return restaurantes.find((restaurant) => restaurant.slug === slug) ?? null;
}